version: '3.8'
services:
  server: 
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
      - /var/run/docker.sock:/var/run/docker.sock
    command: python ./main.py
    restart: always
    tty: true
    networks:
      - default
    ports:
      - 8000:8000
    container_name: fastapi-server

  