version: '3.8'
services:
  db:
    build:
      context: ./src
      dockerfile: db.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    container_name: postgres-db
volumes:
  postgres_data: #

